### PR TITLE
improve step generation

### PR DESCRIPTION
**Pull request by itajaja**
This change improves a couple of things

### better group matching.

There was an imperfection in the regex that made groups too eager. Before `I do "x" and "y"` would have been transformed to `I do (.*)`, while in theory should be `I do (.*) and (.*)`

### show actual strings instead of generic group

This is more opinable, and maybe should go behind some option flag, but if I have a test that says

```
When I click the button "Save"
and I click the button "Close"
and I click the button "Expand"
...
```

the corresponding autogenerated feature would be something like

```ts
when('I click the button (.*)', (args0) => {});
when('I click the button (.*)', (args0) => {});
when('I click the button (.*)', (args0) => {});
```

making it a little hard to understand what's going on just by looking at the test. This change instead generates the following:

```ts
when('I click the button "(Save)"', (args0) => {});
when('I click the button "(Close)"', (args0) => {});
when('I click the button "(Expand)"', (args0) => {});
```

This equally provides `args0` with the quoted content, but also provide a better textual represenation in the the step file

Let me know what you think :) After feedback, I'll make sure to update/add tests

cc @AaronBuxbaum @c0state

### CODE REVIEW

**Comment by itajaja** [comment]
ping 🙌

**Comment by Kradirhamik** [comment]
Looks good! would love to see this merged!

**Comment by itajaja** [comment]
hey @bencompton is this still actively mantained? we have been using this branch for the past month so far and we had no problems, but I don't feel confident without some CI.

**Comment by jtrivett** [comment]
Nice work @itajaja! I would love to see this merged as well. I'm working with a team that is getting started with BDD, jest, and jest-cucumber and this would be a great improvement for them. I only wish I found your PR before I went about solving the "group matching" problem myself today :grin:

I created some tests for the group matching behavior (specifically the `generateCodeFromFeature()` function) that I'd gladly contribute if desired.

**Comment by itajaja** [comment]
I am afraid this package is not very actively mantained. I had to patch the package locally in my projects /shrug

**Comment by itajaja** [comment]
will you cut a new release?

**Comment by bencompton** [comment]
Thanks so much for the contribution, and my apologies that it has taken me until now to find time to review and merge it! I am planning to release all of the changes from this week tomorrow (need to fully regression test everything, etc.).

Yes, I have always found it annoying that the step generation swallows quotes and outputs this:

```javascript
when(/^I click the button (.*)$/, (args0) => {});
```

Instead of this:

```javascript
when(/^I click the button "(.*)"$, (args0) => {});
```

Without the quotes in the regex, the argument that gets passed in contains extra quotes, which isn't very intuitive.

I did change your code a bit so it outputs the above regex, since I think most people would prefer a more generic regex to a regex that includes the specific string in the regex like `/^I click the button "(Save)$/"`.

I also liked that you were separating out the string and numeric matches, and made a tweak so that numeric values like this:

```gherkin
Given I have 5 apples
```

Would generate a regex like this:

```javascript
given(/^I have (\d+) apples$/)
```

**Comment by itajaja** [comment]
great!

> I did change your code a bit so it outputs the above regex, since I think most people would prefer a more generic regex to a regex that includes the specific string in the regex like /^I click the button "(Save)$/".

any chance that can get configured? For us it made our life much easier, so unless this lands in this package, we'd still have to keep using a patched version

**Comment by bencompton** [comment]
I guess I don't understand the reason for having `/^I click the button "(Save)"$/`. Can you provide an example of where this would be beneficial vs. the more generic  `/^I click the button "(.*)"$/`? In either case, "Save" would get passed into your step definition, but the more generic step regex can be reused across multiple steps.

**Comment by AaronBuxbaum** [comment]
The result is the same, but the difference is that the developer's experience is a little better with `"(Save")` IMO. It means you can stay exclusively within the test file while you're working, as opposed to going back and forth. In addition, due to jest-cucumber's generation throwing an error if there's a difference between the test file and the spec, we don't need to worry about them going out of sync.

So, in my mind the tradeoff is a little more maintenance work (when one value changes, you have to change the other), for a more all-in-one developer experience while writing tests

**Comment by bencompton** [comment]
Usually, the quotes mean that you want a generic parameter that gets passed into one step definition, in which you perhaps would have a `switch` statement looking for specific strings (e.g., "Save", "Cancel"), and take the appropriate action. I would think that most users would want that to be the default behavior. If the intention is that each step is going to have a separate step definition, the alternative would be to not quote anything:

```gherkin
When I click the button Save
```

In this case, Jest Cucumber will generate this step definition:

```javascript
        when('I click the button Save', () => {

        });
```

With a string, you get the same developer experience as with the regex `/I click the button "(Save)"$/`. Is the reason for preferring a regex over a string because the quotes in the feature file step are desirable?

Either way, I would think 99% of the time, people will expect the generated regex for quoted values to be `"(.*)"`, and I'm not sure enough people would expect the other behavior (or who are unwilling to use strings instead of regexes) to merit making it configurable.

**Comment by bencompton** [comment]
Actually, I just tested, and this also works: `when('I click the button "Save"')`, but of course, Jest Cucumber won't generate that for you if you have the quotes.

**Comment by AaronBuxbaum** [comment]
The reason we need the matcher is because it forwards that prop into the step definition, so we can make reusable step definitions:
```
when(/I click the button "(Save)"$/, iClickTheButton);
when(/I click the button "(Cancel)"$/, iClickTheButton);
```
You lose that ability if you're doing a 1:1 string match.

There are some other advantages of "(Save)" vs "(.*)":
1. I can reuse the step definitions, for faster iteration of development
2. I can work directly from the test file without having to jump back and forth between the test file and the spec file
3. I can more easily switch to a different Gherkin-based test framework if desired in the future (realistically this is not going to be perfectly smooth, but the strings already being set up means it's significantly closer)
4. It's more consistent with existing Gherkin best practices for step grammar
5. It just reads nicer to me -- particularly for manual testers, it's important to make the specific text to look for stick out vs the concepts surrounding it; for example "I click the button Save" is not as obvious as "I click the button "Save"". In the former, a manual tester might think that it means any save-ish text is the desired button; the latter specifies that I want that specific text

All of this is pretty nitpicky admittedly! We're quite happy with this library and have about 500 integration tests running across two projects. In my "perfect world" scenario the generator would generate the real text from the feature file, and then keep them in sync (ie. "this match differs between the feature file and the test file, which would you prefer?"), but thusfar handling that manually hasn't been a big deal

**Comment by itajaja** [comment]
agree with Aaron's point. we've been working with this change for some time and for us is the best developer experience.

**Comment by itajaja** [comment]
specifically, with the regex, our test files would all read something like

```ts
when(/I click the button "(.*)"$/, ...);
when(/I click the button "(.*)"$/, ...);
when(/I see the text "(.*)"$/, ...);
```

which is pretty meaningless when looking at and to get some context you need to look at the actual gherkin file

**Comment by itajaja** [comment]
we'd love to have this behavior, even if it's behind an option flag. would that work?

**Comment by bencompton** [comment]
I would categorize it as a clever trick, and a matter of taste, but I'm not sure how widespread its use would be. Adding it as an option would still mean that this would be something that needs to be supported and manually regression tested since the existing tests (i.e., examples) can't really test configuration flags. If you want to do another PR with this behind a configuration flag, then I will accept it.

I suppose there are many potential options for how step code is generated. If there are more requests for custom code generation, then it might make sense to have some sort of a plug-in architecture so people can make the step code generation work however they want. I've also seen some attempts at creating IDE plug-ins that generate step code, and more granular step definition preferences hidden away in context menus in such a project could make sense.

**Comment by itajaja** [comment]
sounds good!

**Pull request merged**
