### PR TITLE
support jest 27

### PR DESCRIPTION
**Pull request by j8kin**
Support Jest 27 since it has some breaking changes against previous version of jest 26.

### CODE REVIEW

**Comment by j8kin** [comment]
fixing #131

**Comment by vdhpieter** [comment]
@bencompton Any idea when this can be merged?

**Comment by vdhpieter** [comment]
@bencompton Could you take a look?

**Comment by diestrin** [comment]
Will this ever get merged? I have followed this PRs for a few months already, and this is preventing the project to work properly.

**Comment by bencompton** [comment]
This is now merged and published in v3.0.2 on NPM. Sorry, meant to get this one released ages ago.

**Comment by diestrin** [comment]
Thank you @bencompton, appreciated

**Pull request merged**
