### PR TITLE
output in console scenario outline with example title

### PR DESCRIPTION
**Pull request by romuleald**
Hello,

It adds in the console output the case from the example to avoid duplicated scenario outline title.
Should fix the #19

As I'm not familiar with TypeScript, I did the change first in my local node_module.
Tell me if I need to change something.

Thanks for that great plugin!

### CODE REVIEW

**Comment by romuleald** [comment]
Yes! It's just for the output in console.

It can't run the jest because it don't find babel-jest.


Le jeu. 30 août 2018 à 16:20, Ben Compton <notifications@github.com> a
écrit :

**Comment by bencompton** [comment]
I ran into that problem earlier, and it looks like npm installing babel-jest fixes that.

I would really prefer to see the more general solution like #19 shows where any column from the table can be inserted into the title, rather than depending on a column in the examples table to have a very specific name. For instance, this solution might cause some confusion if someone has an example table with a `title` column that is intended for a purpose other than the scenario title.

**Comment by bencompton** [comment]
You're right, I see that SpecFlow does work this way. From my tests, it looks like it is looking at the first column and appending that value to the title, but it actually doesn't seem to care what the first column is named.

What are your thoughts about making just take the first column and not care about the name? If you're good with that and have some time, it should be a pretty simple change. Otherwise, I can try to find some time in the next couple of days to work on it.

It should just be a matter of passing the example table in addition to the specific example row from `parseScenarioOutlineExampleSet` into `parseScenarioOutlineExample`. From there it can look at the table and figure out what the first column is called to pull it from the example row instead of assuming `title` is the name of the first column.

**Comment by romuleald** [comment]
I will try to take a look this weekend!

I see that SpecFlow and Cucumber diverge on the way to render, I'll give a
try to manage this by options!



Le ven. 31 août 2018 à 15:33, Ben Compton <notifications@github.com> a
écrit :

**Comment by romuleald** [comment]
I made the change, cucumber suggest to have a `<anyKey>` in the scenario outline so I match if it exist then remplace it with the `anyKey` column!
What do you think about this?

Also added:
* **babel-jest** because I had the same problem in local for running test
* `npm run jest` to run `jest --verbose`

**Comment by bencompton** [comment]
Ah, so now it works just like #19. I see you even updated the appropriate example--perfect!

**Comment by bencompton** [comment]
Your change is now published in v1.0.9. Thanks for your contribution!

**Comment by romuleald** [comment]
Oh great!
Thanks for accepting this, we'll be super happy at work :)

**Comment by Tuely** [comment]
How can i get cucumber scenario variables in title?

I am having issue with my scenario name. I am expecting this should generate scenario name as **"Residency as under 1 year"** ..... But actual it's generating as 
**"ResidencyasUKResidiency("Under 1 year","Supplied")"**

Can some one please help me to solve this


Scenario Outline: Residency as <UkResidency>
	Given I have built a policy with the following details
	Then I verify UK Residence Parameter '<UkResidence>'

Examples: 
	| UkResidency    | UkResidence |
	| Under 1 Year   | Supplied    |

**Pull request merged**
