### PR TITLE
Fix scenario outline title placeholder to work with autoBindSteps (Fixes #101)

### LINKED ISSUE #101: Using Scenario Outline title placeholder doesn't work with autoBindSteps
@bencompton 

Hi Ben, It works well when I remove the placeholder from Scenario Outline title. Adding the code I used for reference. Thanks!!

```
//login.feature
Feature: Login
    Scenario Outline: <element> test
        When user is on home page
        Then user verifies <element>

        Examples:

            | element |
            | button   |
            | input      |
```

```
//login.steps.js
const { loadFeatures, autoBindSteps } = require("jest-cucumber");
const { CommonSteps } = require("./common.steps");
const { LoginSteps } = require("./newLogin.steps");
const features = loadFeatures("/Users/techcloset/Desktop/JEST/login.feature");
autoBindSteps(features, [CommonSteps, LoginSteps]);
```

```
Error:   at Object.<anonymous>.exports.checkThatFeatureFileAndStepDefinitionsHaveSameScenarios (node_modules/jest-cucumber/src/validation/scenario-validation.ts:111:15)
      at Suite.<anonymous> (node_modules/jest-cucumber/src/feature-definition-creation.ts:291:9)
      at Object.defineFeature (node_modules/jest-cucumber/src/feature-definition-creation.ts:286:5)
      at node_modules/jest-cucumber/src/automatic-step-binding.ts:30:9
          at Array.forEach (<anonymous>)
      at autoBindSteps (node_modules/jest-cucumber/src/automatic-step-binding.ts:29:14)
      at Object.<anonymous> (login.steps.js:5:1)
```

### PR DESCRIPTION
**Pull request by Papooch**
Fixes: https://github.com/bencompton/jest-cucumber/issues/101

I don't know it it's the right way, but now outline scenarios with variables in the name are resolved correctly.

### CODE REVIEW

**Comment by pplancq** [comment]
@bencompton could you take a look at this PR because in my projects this bug is blocking us a bit and this fix seems relevant to me.
Best regards.

**Comment by Papooch** [comment]
@pplancq I rebased the fix on the current master and opened a new PR: https://github.com/bencompton/jest-cucumber/pull/142

I also pushed the built files on the `dist` branch in my fork as before, so you can try installing that and see if it fixes your issue.

**Comment by bencompton** [comment]
Yes, I should have some time to look at this and other PRs later today, although I see this was closed, so not sure if there is additional work being done here.

**Comment by Papooch** [comment]
@bencompton I have created a new PR just now, you probably missed my earlier comment while writing yours :)

**Comment by bencompton** [comment]
@Papooch - currently getting used to the GitHub iOS app and missed your previous comment. Thanks for the new PR! LGTM and merged.

**Pull request closed without merging**
